### ISSUE TITLE
Add gaussian IRC logfile format parser

### ISSUE THREAD

**Issue by tczorro** [theochem/iodata#140]
Add irc output parser for parsing geo structures from the process

**Comment by tovrstra** [comment]
I'm not sure if it is relevant, but these data can at the moment already be read (with higher precision I guess) from the fchk file. See e.g. https://github.com/theochem/iodata/blob/master/iodata/test/test_fchk.py#L432

I can imagine that it could be relevant to be able to read this information also from a log file, e.g. because some users don't keep fchk files.
