### ISSUE TITLE
Atomic unit for entropy

### ISSUE THREAD

**Issue by fwmeng88** [theochem/iodata#152]
In Q-Chem log file, the entropy comes with the unit of cal/mol.K. How can we convert entropy to the atomic unit? Right now, we are just keeping the original unit.

**Comment by PaulWAyers** [comment]
I think we should just store these "extra features" with clearly specified units. So store the value and the unit. @tovrstra had a nice unit-conversion utility that could be used as needed if we store it with clearly specified units.

**Comment by fwmeng88** [comment]
Thanks, Paul. @PaulWAyers 

Can you share the link of the utility and I store the unit properly? @tovrstra Thanks!

**Comment by FarnazH** [comment]
I think the question is whether we want to convert these extra properties to atomic units (like everything else in IOData) or just keep the original units in the log file (and store the unit of property in IOData as well). I am not sure whether one uses entropy in atomic units, so the user needs to convert it back.

**Comment by PaulWAyers** [comment]
I can't imagine cases where entropy is used in a.u. except maybe in Hubbard models. So I'd suggest either having a name that makes the units very clear or storing units explicitly as a named tuple. I'm curious what @tovrstra can say about unit conversion, I think that he knows more about automatic (or semi-automatic) unit conversion utilities in Python, which is the way we should be going.

**Comment by tovrstra** [comment]
One problem is that, strictly speaking, there is no atomic unit of temperature. One can always decide to use "atomic units + Kelvin" as the internal units by convention, which addresses that point. I'm a bit reluctant to make exceptions on the usage of internal units because it will be a precedent. If we decide to use "atomic units + Kelvin" in all cases, one can avoid future discussions on which values should adhere internal units and which should not. I can imagine people disagreeing easily in such discussions.

One can subclass floats, arrays etc to contain unit information but these add a lot of code complexity, which seems overkill.

**Comment by FarnazH** [comment]
@fwmeng88, based on the above discussion, please convert `entropy` to "atomic units + K" before storing it in `IOData` in PR #149. The conversion factors can be added to the  `utils` module; see https://github.com/theochem/iodata/blob/master/iodata/utils.py#L34

**Comment by fwmeng88** [comment]
Thank you, all!

I have implemented the way Farnaz suggested @FarnazH. Corresponding commits are f81400f, e0d460f, ab9daff and b5c3ffb.
