### ISSUE TITLE
Bad alpha and beta occupation numbers

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/iodata#158]
In the MolecularOrbitals class, there is an issue for alpha and beta occupations.

When the occupations are nearly integers (very close to 0, 1, and 2), then the present rule works.

When the occupations are fractional, it would be more sensible to choose alpha=beta occupations, which is correct for singlets and for the M_{s} = 0 (N_{alpha} = N_{beta}) state associated with doublets, triplets, etc..

I'd recommend detecting whether occupations are near-integer and, if not, using alpha=beta occupations instead (and printing a warning that the code is likely to be reliable except for restricted singlets).

**Comment by tovrstra** [comment]
@PaulWAyers Do you have an example file which could be used for unit testing? Or an idea on how to cook one up?

**Comment by PaulWAyers** [comment]
I think any correlated 1-DM for a singlet state would be a good choice for the "fractional" case; a CISD calculation in Gaussian for the Be atom would be a simple case. The integer case could be tested by a restricted calculation on a non-singlet, e.g. the Nitrogen atom (quaduplet).

**Comment by tovrstra** [comment]
@PaulWAyers  Are you referring to the following? https://github.com/theochem/iodata/blob/master/iodata/orbitals.py#L55

I wrote a simple example to demo this issue, just make sure we're talking about the same thing.

```python
#!/usr/bin/env python
import numpy as np
from iodata import load_one

# Load CISD calculation
iodata = load_one("gaussian.fchk")

# Compute natural orbitals of th CISD WFN. (They are not stored in the FCHK.)
from iodata.overlap import compute_overlap
olp = compute_overlap(iodata.obasis, iodata.atcoords)
tf = np.dot(olp, iodata.mo.coeffsa)
one_rdm_mo = np.dot(tf.T, np.dot(iodata.one_rdms["post_scf"], tf))
evals, evecs = np.linalg.eigh(one_rdm_mo)

# Create an orbitals object with the natural orbitals
from iodata.orbitals import MolecularOrbitals
nbasis, norb = evecs.shape
mo = MolecularOrbitals("restricted", norb, norb, evals, evecs, None, None)

np.set_printoptions(suppress=True)
print("occs")
print(mo.occs)
print("occsa")
print(mo.occsa)
print("occsb")
print(mo.occsb)
```

Which gives as output for a Be CISD calculation:

```
occs
[0.         0.         0.         0.00000624 0.00000624 0.00000624
 0.00000624 0.00000624 0.00000841 0.00000841 0.00000841 0.00001094
 0.00001094 0.00001094 0.00001094 0.00001094 0.00001094 0.00001094
 0.00003506 0.00011362 0.00011362 0.00011362 0.00011362 0.00011362
 0.00332027 0.05968729 0.05968729 0.05968729 1.81685415 2.00002753]
occsa
[0.         0.         0.         0.00000624 0.00000624 0.00000624
 0.00000624 0.00000624 0.00000841 0.00000841 0.00000841 0.00001094
 0.00001094 0.00001094 0.00001094 0.00001094 0.00001094 0.00001094
 0.00003506 0.00011362 0.00011362 0.00011362 0.00011362 0.00011362
 0.00332027 0.05968729 0.05968729 0.05968729 1.         1.        ]
occsb
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.81685415 1.00002753]
```

This is obviously not ok. I'm attaching the example including fchk file.
[occtest.zip](https://github.com/theochem/iodata/files/4995139/occtest.zip)

**Comment by PaulWAyers** [comment]
Yep, this is what I'm referring too. I'm not sure what system you are examining here (looks like it is probably Be), but in this case occsa = occsb is the correct occupations, as it must be for any singlet (or, more generally, for the M_s = 0 state of a multiplet).  The way occsa and occsb was computed here would be appropriate for a R(O)HF calculation.

**Comment by tovrstra** [comment]
Good. Thanks, all is clear now. This is indeed output for Beryllium.

**Comment by PaulWAyers** [comment]
This issue was the one comment (the only semi-critical comment) of the referees for the manuscript, so we should be sure we get it fixed prior to release.

**Comment by tovrstra** [comment]
I'd like to avoid a hacky solution for this, but rather do a minor redesign of the `MolecularOrbitals` class to  handle all cases without special rules for corner cases.

When preparing #245 I noticed a few other related points, which we could address in the design of the `MolecularOrbitals` class. (I did not make any API changes #245 to keep things organized and to allow merging it while API discussion is ongoing.) In addition to the original issue, the following should also be addressed:

- The are a lot of `if self.kind == "..."` conditionals, where `...` can be `restricted`, `unrestricted` or `generalized`. Such conditionals suggest we'd better have three classes for the three kinds of orbitals, derived from the same base class.
- None the attributes and properties with `a` and `b` suffixes (including `norba` and `norbb`) are supported by the `generalized` wavefunction, which suggests a class for the generalized wavefunction should not have these attributes. 

The following class structure would address both points:

```python
class MolecularOrbitals:
    ...

class PureSpinOrbitals(MolecularOrbitals):
    ...
    # In this class and its subclasses, all properties and attributes
    # with a and b suffixes make sense.

class RestrictedOrbitals(PureSpinOrbitals):
    ...

class UnrestrictedOrbitals(PureSpinOrbitals):
    ...

class GeneralizedOrbitals(MolecularOrbitals):
    ...

```

(The first two are abstract base classes.) The main disadvantage would be the extra level of complexity.

To address the original issue, we can follow (at least) two approaches:

- One option is to add an attribute `occs_spinpol`, which contains the difference between the spin up and spindown occupation numbers. (Feel free to suggest other names.) When this is left None, we follow some simple heuristics to derive `occsa` and `occsb` from `occs`. Otherwise, we just use `occsa=(occs+occs_spinpol)/2` and `occsab(occs-occs_spinpol)/2`. This introduce the extra flexibility needed to deal with all corner cases while the behavior of the code remains the same as it was when `occs_spinpol` is not set.
- Another option is to just have `occsa` and `occsb` as attributes and implement `occs` and `occs_spinpol` as derived properties, simply as `occsa+occsb` and `occsa-occsb`. This is the simpler option. However, when one creates a `MolecularOrbitals` instance, one has to provide `occsa` and `occsb` separately, which may be less convenient.

**Comment by PaulWAyers** [comment]
I think the solution (first option) is maybe better. I think somewhere in ChemTools there was a convention discussed that was a bit more explicitly, basically _ab _a _b and _aminusb or something like that to indicate the different quantities. Keeping the "total" occupation numbers (n_alpha + n_beta) and the spin-polarization occupations (n_alpha - n_beta) is preferable I think since it requires less change to the code and allows the most standard cases (Slater determinants) to be treated easily.

Generalized really is just "spin-orbitals" with "occupations" and is so explicit that one doesn't need to deal with this; an alpha-spin-orbital is merely a generalized orbital where all the beta-basis-functions have zero coefficient.
