### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by shivupa** [theochem/iodata#227]
I couldn't import `iodata` when installed using pip from the git repo: `python -m pip install git+https://github.com/theochem/iodata.git --user`

```
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iodata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shiv/.local/lib/python3.9/site-packages/iodata/__init__.py", line 23, in <module>
    from .api import *
  File "/home/shiv/.local/lib/python3.9/site-packages/iodata/api.py", line 47, in <module>
    FORMAT_MODULES = _find_format_modules()
  File "/home/shiv/.local/lib/python3.9/site-packages/iodata/api.py", line 41, in _find_format_modules
    format_module = import_module('iodata.formats.' + module_info.name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/shiv/.local/lib/python3.9/site-packages/iodata/formats/json.py", line 45, in <module>
    from ..version import __version__
ModuleNotFoundError: No module named 'iodata.version'
```

It seems that this line 
`from ..version import __version__`
in this commit caused this?:
https://github.com/theochem/iodata/commit/95e1642d5df88cf086593dd688ad6f7739c09c2d?branch=95e1642d5df88cf086593dd688ad6f7739c09c2d&diff=unified

Sorry I didn't have more time to look into this further. I just caught this when it broke the `cclib` [ci](https://github.com/cclib/cclib/actions/runs/666716114), but this doesn't hold up anything over there since we should be [using the stable pip release instead of the git version.](https://github.com/cclib/cclib/pull/1019)

**Comment by tovrstra** [comment]
We currently don't support installation with pip directly from the repository. The reason is that the `version.py` file is derived from `git describe --tags` when packaging a release. There is currently no fallback option in case the file is not present.

As a workaround for now, you can do the following:

```bash
# Roberto is the tool used for testing and deployment.
pip install roberto --user
git clone https://github.com/theochem/iodata.git
cd iodata
rob write-version
pip install . --user
```

Can you check if this works for you? More details can be found in `CONTRIBUTING.md`

@tczorro This might also be helpful for you.

I'll see if I can insert a stub to make pip install from git work, yet without breaking other things.

**Comment by tovrstra** [comment]
@shivupa Can you try again? It should be fixed (and works on my machine, but please test).

**Comment by shivupa** [comment]
Confirmed working for me! Thanks for the quick turn around on this

**Comment by PaulWAyers** [comment]
Do we need to update the installation documents to reflect this @tovrstra ? @BradenDKelly was having issues also.

**Comment by tovrstra** [comment]
The possibility `python -m pip install git+https://github.com/theochem/iodata.git --user` was never mentioned in the docs, so I didn't worry too much about supporting it.

Given that we still have some pre-1.0 issues to sort out, there is no stable release yet and those who know how to install from git, will be inclined to do it. I'd avoid documenting it, because if it gets used without understanding the implications, it causes more problems than it solves.
