### ISSUE TITLE
[Feature Request]Add Gaussian input type .com and .gjf to load_one

### ISSUE THREAD

**Issue by tczorro** [theochem/iodata#228]
Add gaussian input file support in load_one

**Comment by PaulWAyers** [comment]
I think this is sensible since sometimes databases are provided only as files (either input files for a specific program or something similar) that need to be (re)run locally. When this is the case, parsing the input files can be important for a workflow. So whenever an problem like this comes up, it would be good to use the problem as an impetus to improve/extend IOData instead of writing a one-off script.

**Comment by tovrstra** [comment]
This would indeed be a nice addition. I'll take a closer look at the PR soon.

**Comment by tovrstra** [comment]
Fixed by merging #229
