### ISSUE TITLE
Steal all load functions from tamkin

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#36]
See
- https://github.com/molmod/tamkin/tree/master/tamkin/io
- https://github.com/molmod/tamkin/blob/master/tamkin/test/test_io.py
- https://github.com/molmod/tamkin/tree/master/tamkin/data/test

**Comment by fwmeng88** [comment]
I am working this issue by starting with CHARMM file format, https://github.com/molmod/tamkin/blob/a15141745c90abbe8dadb1394f538e30a3523d48/tamkin/io/charmm.py#L51-L138. I am wondering if you can help with some questions regarding CHARMM file format. 
1. Should the load functions be dependent or independent of tamkin? I think tamkin is built with Python 2 where we run over some exceptions errors when testing. For example, the `print` in https://github.com/molmod/tamkin/blob/a15141745c90abbe8dadb1394f538e30a3523d48/tamkin/partf.py#L1019 will result in an error in Python 3.7.
2. I am not sure which kind of information should be returned at the end of functions. I just copied the `load_molecule_charmm` and `load_coordinates_charmm` where I don't know if there is any need for `load_peptide_info_charmm`. I didn't take the `load_modes_charmm` bacuase I think the normal mode analysis is not our intention.
I will try to port codes from _cpmd.py, gamess.py, gaussian.py, qchem.py and vasp.py_ in the coming days.
Thank you very much! @tovrstra @FarnazH

**Comment by PaulWAyers** [comment]
It's my impression that the goal is to steal the wavefunction-loading capabilities of tamkin.  Tamkin should not be a dependence (just rewrite clean Python 3 code using tamkin code as a starting point); and I would not have started with CHARMM, which I think is probably not the point at all of this issue, since HORTON is a wavefunction method and I am do not think CHARMM has wavefunction information.  Certainly load_peptide_info_charmm is not needed (or even useful, I suspect).

@tovrstra knows better what CHARMM has, if anything, that is useful in the iodata context. Perhaps only the geometry and the charge?

**Comment by FarnazH** [comment]
I think it would be good to start with something simpler like `qchem.py`.

As @PaulWAyers mentioned, the code you port shouldn't add any extra dependency. I also think any information in the output files are worth extracting, as `iodata` is a parsing module in some sense.  I'll leave specific questionss regarding `CHARMM` to @tovrstra.

**Comment by fwmeng88** [comment]
In order to fix the extra dependency problem, I was trying to steal codes from `tamkin` and `molmod`. 

The problem I have right now I don't know do we need `tamkin.data.Molecule` for  `qchem.py` in `iodata`, https://github.com/molmod/tamkin/blob/a15141745c90abbe8dadb1394f538e30a3523d48/tamkin/io/qchem.py#L162. The original code for `Molcule` module can be found at https://github.com/molmod/tamkin/blob/master/tamkin/data.py. Moreover, if we need to port the codes of  `Molcule` module, we need to copy all the codes for the following building blocks. Is it worth doing that? Or, we don't need it? My guess is we can leave it right now, but not sure. Thanks. @FarnazH @tovrstra 
```
from tamkin.geom import transrot_basis
from molmod import Molecule as BaseMolecule, \
    MolecularGraph, ReadOnly, UnitCell, ReadOnlyAttribute
from molmod.periodic import periodic
from molmod.graphs import cached
```

Other dependency probems for `cpmd.py`,  `gamess.py`, `qchem.py` include
```
from molmod.periodic import periodic
from molmod.io import PunchFile
from molmod import angstrom, amu, calorie, avogadro
from molmod.io.common import SlicedReader
```
All these can be fixed by copy and paste the codes from `molmod`. Thanks.

**Comment by tovrstra** [comment]
The `Molecule` class from MolMod would add a lot of non-essential code to IOData (and to be honest, this Molecule class not something I'm particularly proud of), so please discard it. Similarly, instead of copying over the whole `MolecularGraph` and `Graph` classes from MolMod, it would be sufficient to store in IOData just an attribute `bonds` with the list of bonded atom pairs. In general, practically everything that can be read from files with MolMod can be cast into a set of IOData attributes discussed in #41, such that all the boilerplate code from MolMod can be dropped.

**Comment by fwmeng88** [comment]
A useful link for setting up GAMESS output files on Compute Canada, which has the 2017 version of GAMESS, https://docs.computecanada.ca/wiki/GAMESS-US.

http://myweb.liu.edu/~nmatsuna/gamess/tests.html

**Comment by evohringer** [comment]
Thanks @fwmeng88. We will start working on this soon.

**Comment by FarnazH** [comment]
@evohringer and @tovrstra can you please decide what to do with these formats left from `tamkin`: https://github.com/molmod/tamkin/tree/master/tamkin/io

1. `charmm`
2. `cp2k` molecule
3. `cpmd`
4. `trajectory`
5. `vasp`

**Comment by PaulWAyers** [comment]
Perhaps @evohringer and @tovrstra could make a priority-order list of which file formats are most important, in case anyone is inclined to add support? @BradenDKelly is adding *.mwfn (multiwfn) and of the ones I saw, the ability to parse a GAMESS punch file would be relevant, as then we'd have reasonable support for GAMESS, Psi4, Gaussian, Orca, and Q-Chem (at least), which covers a lot of the quantum chemistry space at least.

**Comment by FarnazH** [comment]
Similar to `gromacs` parser mentioned in issue #37, based on my understanding, `charmm` parser in `tamkin` loaded information not existing in PDB format.

**Comment by evohringer** [comment]
@FarnazH : The charmm coordinate parser will be implemented as the "charmm.py" format by @lmacaya .
